version: '3'
services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: ["mvn", "-X", "-f", "/app/pom.xml", "test"]
    volumes:
      - .:/app

#  docker-compose exec tests mvn test - запускаем тесты внутри контейнера
# docker-compose down  - после выполнения контейнера останавливаем этой командой
