spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db?currentSchema=wallet
    username: postgres
    password: wallet
    driver-class-name: org.postgresql.Driver
  application:
    name: wallet_service
