version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data

  tests:
        build:
          context: .
          dockerfile: Dockerfile

        depends_on:
          - db
        command: ["mvn", "test"]
        volumes:
          - ./tests:/test

#  docker-compose exec tests mvn test - запускаем тесты внутри контейнера
# docker-compose down  - после выполнения контейнера останавливаем этой командой
