version: '3'
services:
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=C --lc-ctype=C
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./liquibase:/liquibase

volumes:
  db-data:

