version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet_db

    ports:
      - "5432:5432"


